[package]
name = "alvr_filesystem"
version = "18.21.0"
authors = ["alvr-org", "Patrick Nicolas <patricknicolas@laposte.net>"]
license = "MIT"
edition = "2024"

[dependencies]
lazy_static = "1"
dirs = "6"

[target.'cfg(unix)'.dependencies]
regex = "1"